# Generated by Django 4.0.3 on 2022-03-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='photo',
        ),
    ]
